config/routes.rb
Rails.application.routes.draw do
  resources :tasks, only: [:index, :create]

  if Rails.env.development?
    resources :screens, only: [:index, :show]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dao.rb
module Dao
  def self.table_name_prefix
    'dao_'
  end
end

app/models/dao/task.rb
class Dao::Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/screens_controller.rb
class ScreensController < ApplicationController

  def show
    render params[:id]
  end
end

app/controllers/tasks_controller.rb
# frozen_string_literal: true

class TasksController < ApplicationController

  def index
    @tasks = TaskListQuery.call
    @form = CreateTaskForm.new
  end

  def create
    @form = CreateTaskForm.new(create_params)

    if @form.valid?
      usecase = CreateTaskUsecase.new
      usecase.run(@form.content, description: @form.description, priority: @form.priority, deadline: @form.deadline)
      redirect_to tasks_path
    else
      render :new
    end
  end

  private

  def create_params
    params.require(:form).permit(:content, :description, :priority, :deadline)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Taskbase</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/screens/index.html.erb
<h1>
  Taskbase Screens
</h1>
<ul>
  <li>
    <%= link_to 'Task List', screen_path(:task_list) %>
  </li>
</ul>

app/views/screens/task_list.html.erb
<% tasks = [
  {
    status: '未着手',
    priority: '高',
    content: 'IE11で確認する',
    due_date: '2020/03/30'
  },
  {
    status: '着手中',
    priority: '低',
    content: 'masterをマージする',
    due_date: '2020/04/05'
  },
  {
    status: '完了',
    priority: '中',
    content: 'stgにデプロイする',
    due_date: '2020/03/18'
  }
] %>
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-11 page">
      <div class="page__header">
        <h1>
          Tasks
        </h1>
      </div>
      <div class="task-list">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>
                内容
              </th>
              <th>
                ステータス
              </th>
              <th>
                優先度
              </th>
              <th>
                終了期限
              </th>
            </tr>
          </thead>
          <tbody>
            <% tasks.each do |task| %>
              <tr>
                <td>
                  <p class="task__content">
                    <%= task[:content] %>
                  </p>
                  <p class="task__description">
                    タスクの説明<br />
                    タスクの説明は省略できます。
                  </p>
                </td>
                <td>
                  <%= task[:status] %>
                </td>
                <td>
                  <%= task[:priority] %>
                </td>
                <td>
                  <%= task[:due_date] %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
      <div class="task-list-page__form">
        <div class="row justify-content-center">
          <div class="col-lg-6">
            <h2>
              新規タスク
            </h2>
            <form>
              <div class="form-group">
                <label>
                  内容
                </label>
                <input type="text" class="form-control" />
              </div>
              <div class="form-group">
                <label>
                  説明
                </label>
                <textarea class="form-control"></textarea>
              </div>
              <div class="form-group">
                <label>
                  優先度
                </label>
                <div>
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" id="priority0">
                    <label class="form-check-label" for="priority0">
                      高
                    </label>
                  </div>
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" id="priority1" checked>
                    <label class="form-check-label" for="priority1">
                      中
                    </label>
                  </div>
                  <div class="form-check form-check-inline">
                    <input class="form-check-input" type="radio" id="priority1">
                    <label class="form-check-label" for="priority1">
                      低
                    </label>
                  </div>
                </div>
              </div>
              <div class="form-group">
                <label>
                  終了期限
                </label>
                <input class="form-control" type="date" />
              </div>
              <button class="btn btn-success" type="submit">
                追加する
              </button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>

app/views/tasks/_form.html.erb
<%= form_with model: form, scope: :form, url: tasks_path, html: { id: 'js-new-task-form', data: { test: :new_task_form } } do |f| %>
  <div class="form-group">
    <%= f.label :content %>
    <%= f.text_area :content, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :priority %>
    <div>
      <%= f.collection_radio_buttons :priority, f.object.priorities, :to_i, :to_s do |b| %>
        <div class="form-check form-check-inline">
          <%= b.label(class: 'form-check-label') { b.radio_button(class: 'form-check-input') + t(b.text, scope: 'domain.task.priority') } %>
        </div>
      <% end -%>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :deadline %>
    <%= f.date_field :deadline, class: 'form-control' %>
  </div>
  <%= f.button t('actions.add'), class: 'btn btn-success' %>
<% end %>

app/views/tasks/_list.html.erb
<table class="table">
  <thead>
    <tr>
      <th class="task-list__content">
        内容
      </th>
      <th class="task-list__status">
        ステータス
      </th>
      <th class="task-list__priority">
        優先度
      </th>
      <th class="task-list__deadline">
        終了期限
      </th>
    </tr>
  </thead>
  <tbody data-test="task_list_body">
    <%= render partial: 'task', collection: tasks %>
  </tbody>
</table>

app/views/tasks/_task.html.erb
<tr>
  <td data-controller="expander" data-expander-is-expanded="n">
    <div class="task-content">
      <p class="task__content">
        <%= task.content %>
      </p>
      <% if task.description %>
        <%= link_to t('.description'), '#', data: { action: 'expander#toggle' } %>
      <% end -%>
    </div>
    <div data-target="expander.content">
      <%= task.description && simple_format(task.description, class: 'task__description') %>
    </div>
  </td>
  <td>
    <%=t task.status, scope: 'domain.task.status' %>
  </td>
  <td>
    <%=t task.priority, scope: 'domain.task.priority' %>
  </td>
  <td>
    <%= task.deadline %>
  </td>
</tr>

app/views/tasks/index.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-lg-11 page">
      <div class="page__header">
        <h1>
          Tasks
        </h1>
      </div>
      <div class="task-list">
        <% if @tasks.empty? -%>
          <%=t '.empty' %>
        <% else -%>
          <%= render partial: 'list', locals: { tasks: @tasks } %>
        <% end -%>
      </div>
      <div class="task-list-page__form">
        <div class="row justify-content-center">
          <div class="col-lg-6 task-list-page__form-bg">
            <h2>
              新規タスク
            </h2>
            <%= render partial: 'form', locals: { form: @form } %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/tasks/new.js.erb
$('#js-new-task-form').replaceWith('<%=j render partial: 'form', locals: { form: @form } %>')